apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-deployment
  labels:
    env: gcp
spec:
  replicas: 2
  selector:
    matchLabels:
      env: gcp
  template:
    metadata:
      labels:
        env: gcp
    spec:
      containers:
      - name: gcp
        image: nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
